apiVersion: v1
kind: Pod
metadata:
  name: spod2
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      envFrom:
        - secretRef:
            name: db
